### ISSUE TITLE
error: ‘BYTE_TYPE_G920_XONE’ undeclared

### ISSUE THREAD

**Issue by ytak01** [matlo/GIMX-firmwares#3]
I tried to compile "EMUG920XONE", but I could not compile with the error below.

Making EMUG920XONE:
* atmega32u4
emu.c: In function ‘handle_packet’:
emu.c:117:23: error: ‘BYTE_TYPE_G920_XONE’ undeclared (first use in this function)
       Serial_SendByte(BYTE_TYPE_G920_XONE);
                       ^
emu.c:117:23: note: each undeclared identifier is reported only once for each function it appears in
make: *** [emu.o] Error 1

The definition of "BYTE_TYPE_G920_XONE" is It does not appear to be in "adapter_protocol.h".
Could you please define it?

**Comment by matlo** [comment]
This firmware has not been released yet.
